/// Flutter icons JNoteIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JNoteIcons
///      fonts:
///       - asset: fonts/JNoteIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class JNoteIcons {
  JNoteIcons._();

  static const _kFontFam = 'JNoteIcons';
  static const String _kFontPkg = 'jnote';

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData completed = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inprogress = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
